<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Comedy</name>
   <tag></tag>
   <elementGuidId>616b2da3-970c-49f2-a7c0-634cde68d265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appContainer']/nav/div[2]/a[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>44c2e7ac-bec5-4096-9323-7d2df651b7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> AppNavbar_navItem___QI5L</value>
      <webElementGuid>4e54833d-3575-4194-9672-e70c2bc71050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>appnavbar_menuitem_comedy</value>
      <webElementGuid>47425e9d-cb9c-4ca1-86b6-4678cc09ae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comedy</value>
      <webElementGuid>2a9094a9-5c54-402d-9068-dd71974ea8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appContainer&quot;)/nav[@class=&quot;AppNavbar_navContainer__Pghbj&quot;]/div[@class=&quot;AppNavbar_navbar___zLKe&quot;]/a[@class=&quot;normalisedLink&quot;]/span[@class=&quot;AppNavbar_navItem___QI5L&quot;]</value>
      <webElementGuid>7bb32a79-8127-4e48-a921-6fa3e7ef3aea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appContainer']/nav/div[2]/a[6]/span</value>
      <webElementGuid>ec3a4e3e-63be-4ef8-9aca-d9085a73bd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/span</value>
      <webElementGuid>1cf5c210-f687-4f50-ad4f-965af352b29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Comedy' or . = 'Comedy')]</value>
      <webElementGuid>106dbdc6-17a5-44e5-8ffc-54a641f88b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
