<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>95749994-88cd-4843-9e2a-e6a333368302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-flyout-mkt-change']/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.icp-mkt-change-lnk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28c1c10e-08a4-4471-8f7e-9c5e7af903cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icp-mkt-change-lnk</value>
      <webElementGuid>abb84c39-baf6-4a4d-bd40-843cda30bc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>देश/क्षेत्र बदलें.</value>
      <webElementGuid>df06c8a7-dbe3-44aa-9b3b-c879e4710f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-icp&quot;)/div[@class=&quot;nav-template nav-flyout-content nav-tpl-itemList&quot;]/a[@id=&quot;icp-flyout-mkt-change&quot;]/span[@class=&quot;nav-text&quot;]/div[@class=&quot;icp-mkt-change-lnk&quot;]</value>
      <webElementGuid>fa9556e5-58b6-40e5-a6ad-614792317bff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='icp-flyout-mkt-change']/span/div</value>
      <webElementGuid>6b13e489-3bf5-471f-8767-9c038ba52bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[10]/span/div</value>
      <webElementGuid>86c880aa-6c96-4deb-9db7-b8c409bc905f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'देश/क्षेत्र बदलें.' or . = 'देश/क्षेत्र बदलें.')]</value>
      <webElementGuid>b155be03-c46c-4953-b4bf-e3e98f23fcc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
