<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Hello, sign in</name>
   <tag></tag>
   <elementGuidId>f0a5bb69-b074-4261-ae20-8b38424ab0b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hmenu-customer-name > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-customer-name']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>b89b59fc-2e19-4194-9bad-f5e4e99d8750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello, sign in</value>
      <webElementGuid>26d0f97a-1e5b-463b-ae0b-acbb631c572b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-customer-name&quot;)/b[1]</value>
      <webElementGuid>e9eb6a01-9ab2-4025-adcf-6b731c975110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-customer-name']/b</value>
      <webElementGuid>a94c7a24-ed3c-407f-b319-434f381303d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/b</value>
      <webElementGuid>14ec29a8-affe-4a97-af44-dd38a9f0bcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Hello, sign in' or . = 'Hello, sign in')]</value>
      <webElementGuid>5de3eab2-6a2b-47d2-a1cc-30015683d10d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
