<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___sif_encryptedVPA_collect</name>
   <tag></tag>
   <elementGuidId>998914a2-4aed-4cfb-b639-d7d6ce0b93a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-aJblg7-116</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e89debd9-0955-456c-a9d5-96eacb1fc304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2d542ca-ff36-4dad-86b8-eed900687d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-aJblg7-116</value>
      <webElementGuid>bff9a925-1280-4098-af2d-62be810ec1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter UPI ID</value>
      <webElementGuid>f386cc3a-b7f7-47a8-9b80-099ca78cac32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__sif_encryptedVPA_collect</value>
      <webElementGuid>b8921b8d-87fa-4435-8bb4-0c8ed4611656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bce3f3ca-144b-4033-872b-a98912ebb06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-form-normal no-prefetch-on-change</value>
      <webElementGuid>d1f530c8-9454-4171-8333-ff599e33c2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-aJblg7-116&quot;)</value>
      <webElementGuid>115290f6-a063-4c36-a5e0-b5cd3b139559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-aJblg7-116']</value>
      <webElementGuid>6f850224-ab3c-4a89-bd53-c90bfa2f179b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-aJblg7-131']/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>3e9f6f9e-acd4-421a-b7f2-f7509b6fdf96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>938a0bbe-0ffa-431e-88d6-72a25a29fd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pp-aJblg7-116' and @placeholder = 'Enter UPI ID' and @name = '__sif_encryptedVPA_collect']</value>
      <webElementGuid>ade48042-a921-4e9d-83e8-d005aff7969e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
