<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>d614adbd-d6d5-492e-a17a-19b8387127af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-aJblg7-128</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1572b862-c9a0-40c0-b08c-bab554cf2704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-aJblg7-128</value>
      <webElementGuid>8d36ee4a-7746-4cf4-bbb2-1dbf8b7ecccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c4d72596-ee86-4831-9116-7918f8596fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>5c3f232a-946a-4f81-af95-b6d776576885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=amzn1.pm.poa.YW16bjEucG9hOmFtem4xLnBvYS5wb2RhLlVuaWZpZWRQYXltZW50c0ludGVyZmFjZTox.QTNEVFNPUlE5TEs1QU8&amp;isExpired=false&amp;paymentMethod=UnifiedPaymentsInterface&amp;tfxEligible=false</value>
      <webElementGuid>59ba6e63-7405-4480-bb68-69d0237ae7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-aJblg7-128&quot;)</value>
      <webElementGuid>5e09169b-df1f-4e19-8646-dba883faacfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-aJblg7-128']</value>
      <webElementGuid>98488e9f-93f8-4c26-acb4-67e148e47463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-aJblg7-127']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>ba1a351d-a7e0-425a-9099-e7b7f74a52ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/input</value>
      <webElementGuid>ecc36307-5094-4016-b326-8110515a20c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-aJblg7-128' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>5c753fa0-8423-488b-ab9b-3b8e29c2a4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
