<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-widgetEventValidateUpiIdEvent</name>
   <tag></tag>
   <elementGuidId>0351e87e-2f94-4b67-b2ac-22d86cc7332b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ppw-widgetEvent:ValidateUpiIdEvent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ppw-widgetEvent:ValidateUpiIdEvent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71d2aacd-3e15-484a-a591-1cec97b35dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-widgetEvent:ValidateUpiIdEvent</value>
      <webElementGuid>9022ebdd-0dad-42f6-b32d-b5b845e36ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-button-text</value>
      <webElementGuid>0bee887f-8537-46d0-9ea4-977998adf376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0f7e0615-ddf2-48ec-a109-e1cd041af0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>pp-aJblg7-117-announce</value>
      <webElementGuid>3141dfbf-1c70-49b6-85cf-693ee83f783f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-aJblg7-117&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input a-button-text&quot;]</value>
      <webElementGuid>2548b312-9f58-44ab-9c48-f973fb2c3c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ppw-widgetEvent:ValidateUpiIdEvent']</value>
      <webElementGuid>cb44f41d-875d-459b-b34e-1fc5bbe92406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pp-aJblg7-117']/span/input</value>
      <webElementGuid>1b7381d3-998b-4964-8c13-01802b669c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/input</value>
      <webElementGuid>60d6fb9e-00e6-4497-81a6-c34c60dc062b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ppw-widgetEvent:ValidateUpiIdEvent' and @type = 'submit']</value>
      <webElementGuid>6b360e40-76ab-4980-bf0a-5a9f809362c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
