<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-widgetEventSetPaymentPlanSelectCo_b3daea</name>
   <tag></tag>
   <elementGuidId>bde23282-0256-45cc-9b34-4ab29579e7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ppw-widgetEvent:SetPaymentPlanSelectContinueEvent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ppw-widgetEvent:SetPaymentPlanSelectContinueEvent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>326f9290-394d-4d22-abc3-593fa412dc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-widgetEvent:SetPaymentPlanSelectContinueEvent</value>
      <webElementGuid>306f731a-2998-4c7e-971d-3c881b49853d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pmts-component-id</name>
      <type>Main</type>
      <value>pp-aJblg7-6</value>
      <webElementGuid>9f942345-dd9c-471f-bc2b-fae8bbe22c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-button-text</value>
      <webElementGuid>0cd7543f-d6da-41cb-9fda-8f29f1be5e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a7477e7e-1bb3-49bf-b48d-f4b029b2d9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>pp-aJblg7-148-announce</value>
      <webElementGuid>97b73f2b-1e85-4703-b019-330350be8c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-aJblg7-148&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input a-button-text&quot;]</value>
      <webElementGuid>5ae7266e-c7ce-4b9c-ab2b-142769dbb2ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ppw-widgetEvent:SetPaymentPlanSelectContinueEvent']</value>
      <webElementGuid>e52f6e6f-21d6-47f3-89ed-ef6a0cf13843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pp-aJblg7-148']/span/input</value>
      <webElementGuid>ee9c27f7-3698-467a-a906-1790255f41bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/input</value>
      <webElementGuid>001e81f5-67c9-4d3e-9b76-67ebbf3fdd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ppw-widgetEvent:SetPaymentPlanSelectContinueEvent' and @type = 'submit']</value>
      <webElementGuid>6ed7c63b-54ed-46aa-90af-f856cf81d1fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
