<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_hm-icon nav-sprite</name>
   <tag></tag>
   <elementGuidId>f34524ae-be1f-4d7c-a9ff-d7532b652165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-hamburger-menu']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.hm-icon.nav-sprite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a63355bc-6f9c-4fe5-a71d-625cbf58f8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hm-icon nav-sprite</value>
      <webElementGuid>f27ce664-e268-4cd1-8853-63113ae2121d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-hamburger-menu&quot;)/i[@class=&quot;hm-icon nav-sprite&quot;]</value>
      <webElementGuid>87bd2685-7e19-4cbb-90d4-9209cd0ce886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-hamburger-menu']/i</value>
      <webElementGuid>ef3239af-22c1-4ade-b890-33e06d8740ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>6c26611a-e9ed-4b1a-bc9b-dbcfd3194367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
