<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_address-ui-widgets-landmark</name>
   <tag></tag>
   <elementGuidId>55dc7c2b-c653-4cc6-97e4-03b339ddb6d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-ui-widgets-landmark']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-landmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36657d9c-94e2-47e1-bf5b-32766465eabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d51164be-6e65-4c0a-a5e6-4ec159e55939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>b8906aaa-8088-4ba9-b159-15a670985a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-landmark</value>
      <webElementGuid>89e1c74f-e532-471d-9ff4-1b326fef9a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.g. near apollo hospital</value>
      <webElementGuid>bf66dce0-4108-4890-ad89-55c54ce22979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-landmark</value>
      <webElementGuid>58015df6-0513-44cf-80ee-7e715196e93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b88dff8f-21a9-4e28-a99b-d813df37dfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text address-ui-widgets-desktop-form-field-full-width addrui-form-text-input</value>
      <webElementGuid>0317f0d8-2045-4bfd-825d-3183b38c0efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Landmark</value>
      <webElementGuid>d03fea62-86b6-4f1e-852c-23054c5f3836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-landmark&quot;)</value>
      <webElementGuid>83aee00a-191e-4569-81a0-e8cc918a1c19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-ui-widgets-landmark']</value>
      <webElementGuid>21f01ec9-c3b5-4656-9f9d-e9cc752cf660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[14]/input</value>
      <webElementGuid>29156934-b6aa-4be4-a391-be65e9e9c8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input</value>
      <webElementGuid>a040ef95-1427-48bc-939d-f6cae8caf4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-ui-widgets-landmark' and @placeholder = 'E.g. near apollo hospital' and @name = 'address-ui-widgets-landmark']</value>
      <webElementGuid>52f86071-00f7-4e5f-9bc1-6d651a4c4306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
