<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_address-ui-widgets-enterAddressPostalCode</name>
   <tag></tag>
   <elementGuidId>090e80a1-cb07-42cd-9966-bea34f2073de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-ui-widgets-enterAddressPostalCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-enterAddressPostalCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d17b6c4-3460-486e-b1be-f9cbcd1c710d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9553722-fc22-48ea-a8d4-27a7800baba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>cdb73199-86c2-43e8-bf9c-1b99b2aa2871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressPostalCode</value>
      <webElementGuid>c778871e-a036-4fed-a63d-97d82d93b735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>6 digits [0-9] PIN code</value>
      <webElementGuid>90dc66b5-0af2-4f8e-9f7d-8c989609821b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressPostalCode</value>
      <webElementGuid>e5bc09aa-caaf-4f8c-a986-b0912ba9844e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39ae53dc-cf67-44fa-affd-12e1c5900523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text address-ui-widgets-desktop-form-field-full-width addrui-form-text-input</value>
      <webElementGuid>61fa6960-4883-47be-b53b-ee47534e7b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Pincode</value>
      <webElementGuid>cb5c6d79-3f2a-4161-9653-937c4df906a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressPostalCode&quot;)</value>
      <webElementGuid>e01cf9b0-0822-4ea3-8c14-4e90d73401eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-ui-widgets-enterAddressPostalCode']</value>
      <webElementGuid>126213b3-2138-4102-97dd-076145156f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[8]/input</value>
      <webElementGuid>b894928c-2b3d-4140-9380-8e957a34f8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>dfa5a6b6-b5dd-4b62-b58e-dfcc81c4162a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-ui-widgets-enterAddressPostalCode' and @placeholder = '6 digits [0-9] PIN code' and @name = 'address-ui-widgets-enterAddressPostalCode']</value>
      <webElementGuid>5c2c94c4-fd0d-48ab-9cd9-7a5ab8324526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
