<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_or</name>
   <tag></tag>
   <elementGuidId>c0dd4545-fe59-457f-87f6-d5cd45984b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>c30fc306-6055-462e-b488-214b9bc02920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>405bb92e-784e-43f3-9e63-9cee731f4acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>or</value>
      <webElementGuid>0caac3b8-19ae-4fb3-bba6-0410ec6a9bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap-signin-alternative-option-divider&quot;)/div[@class=&quot;a-divider a-divider-break&quot;]/h5[1]</value>
      <webElementGuid>2a8484e0-447f-45c4-adf9-614f8c2e9a79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ap-signin-alternative-option-divider']/div/h5</value>
      <webElementGuid>fc1395db-d75d-4c2a-8a93-8dd63808b7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>36656f36-1d38-474f-b334-9d085bb98f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'or' or . = 'or')]</value>
      <webElementGuid>2531c491-0c2f-4cd6-9d21-5e0f235db4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
