<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JHARKHAND</name>
   <tag></tag>
   <elementGuidId>50e04f72-7c61-4453-8af1-91c2e4d65427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e3f0e75-247f-4231-8e9a-9b606b63fb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3e001df6-6d5c-49b2-b5a4-c6aa01d53459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e45f37ac-b4af-410b-81e5-be671015ee96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f1027bf-7c56-4d6f-bcc3-fe52d706da78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;JHARKHAND&quot;}</value>
      <webElementGuid>9439dde1-747f-43b9-9824-6064ac8224f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_14</value>
      <webElementGuid>b25a951a-ffe5-4204-a05b-9952d297d2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link a-active</value>
      <webElementGuid>e576ecc6-6afe-4407-9fa7-0b4c95b2231d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JHARKHAND</value>
      <webElementGuid>9e414353-8c79-4852-976f-ba20ef99ce6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_14&quot;)</value>
      <webElementGuid>ae2a25fe-cf7d-4cb9-8ff6-e9c769bdd270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_14']</value>
      <webElementGuid>9e4e0cc5-7e0e-478c-94e3-c2261abd2527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-2']/div/div/ul/li[15]/a</value>
      <webElementGuid>38f7d986-f10e-4071-a54c-a4203fa3d062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JHARKHAND')]</value>
      <webElementGuid>3154530e-3339-4dd7-bbe0-11cd7c86082b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[16]</value>
      <webElementGuid>652cc9dd-25c3-40a6-b06b-1cd6f07ebeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/a</value>
      <webElementGuid>3e3287d9-bc88-4a4c-9d90-e37dc534943e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_14' and (text() = 'JHARKHAND' or . = 'JHARKHAND')]</value>
      <webElementGuid>8638ce6e-2dd3-4e62-b483-b027a4a124b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
