<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_a-icon a-icon-close</name>
   <tag></tag>
   <elementGuidId>2561ecf2-0d75-41a1-b0b9-512113da4e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.a-icon.a-icon-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a-popover-1']/div/header/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d339e9a2-f4d8-401b-9989-ad6424f0481e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-close</value>
      <webElementGuid>b2efb3ba-6b4a-412a-b37c-b6e0577e0e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-1&quot;)/div[@class=&quot;a-popover-wrapper&quot;]/header[@class=&quot;a-popover-header&quot;]/button[@class=&quot;a-button-close a-declarative&quot;]/i[@class=&quot;a-icon a-icon-close&quot;]</value>
      <webElementGuid>c3ca7842-ebf4-44f6-9288-3bfc9dc8d2ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/header/button/i</value>
      <webElementGuid>af174fd9-5d00-4efc-acd3-a3a35348293c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>df84b762-018a-4f54-9340-1393095e3db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
