<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>cee18b50-74ce-48f7-b804-b6b40572aa8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ap_phone_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ap_phone_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4480071-b663-4821-9c20-15a2c2cca7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>47214171-afee-4a6e-857a-a7c857a8ee6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8740c5af-a5ad-488e-a06d-b53c8a8b6b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_phone_number</value>
      <webElementGuid>638efd4f-84c6-4060-86da-d1103c6db7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>432304f2-4b40-4b00-8fc7-479bd083719c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile number</value>
      <webElementGuid>53dfbec9-77b8-4da0-8c7e-ef9d78fd71c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9646c4ca-0a6c-47fb-b714-34d9017d66f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b06d1296-9a00-47a1-8997-ec185932f615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 a-spacing-micro auth-required-field auth-require-phone-validation</value>
      <webElementGuid>dc50623f-59c1-4f77-8a1e-8990cb63ee5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-id</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>d1fa2ee8-6d39-4d31-9987-759a96b16940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_phone_number&quot;)</value>
      <webElementGuid>459f09d4-a29f-4f93-919e-d2d339cd7436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ap_phone_number']</value>
      <webElementGuid>7b47e76b-ccab-4145-8249-851ba518286f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ap_register_form']/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>e79807bc-2e30-4813-b080-801fa14a5faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1181958a-1559-4b7d-bb8b-4151057c295d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'ap_phone_number' and @placeholder = 'Mobile number' and @name = 'email']</value>
      <webElementGuid>559555e8-8832-4bfe-ad7f-590c38eef141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
